### ISSUE TITLE
Nesting of properties

### ISSUE THREAD

**Issue by bananafunctor** [ismaelga/react-json-editor#10]
Currently there seems to be an issue with the nesting of properties,

```
var schema = {
  type : "object",
  properties: {
    comment: {
      title: "Comment",
      type: "string"
    },
    "color": {
      "type": "object",
      "properties": {
        "hasFave": {
          "title": "Do you have a favourite colour?",
          "type": "string"
        }
      },
      "oneOf": [
        {},
        {
          "properties": {
            "hasFave": {
              "enum": ["no"]
            }
          }
        },
        {
          "properties": {
            "hasFave": {
              "enum": ["yes"],
              "fave": {
                "title": "Your favourite colour",
                "type": "string",
                "enum": ["-", "red", "green", "blue" ]
              }
            }
          }
        }
      ],
      "x-hints": {
        "form": {
          "selector": "hasFave"
        }
      }
    }
  }
};
```

The 'fave' property will not render now, this can be remedied by moving the 'fave' property up one level, but that will only make it a pseudo child of 'hasFave' (i.e the path of fave will be ['color', 'fave'] not ['color', 'hasFave', 'fave'] as it should be.

**Comment by ismaelga** [comment]
`hasFave` is already a property of type string. So it can't have children. IMO having `color/fave` and `color/hasFave` is the way to go.

**Comment by bananafunctor** [comment]
What could be done is to make it so that selection of string will yield an internal value like 
`{ 'value' : 'foo' }` this would make it so that you could nest like like I mentioned.

**Comment by ismaelga** [comment]
The thing is, you have defined that hasFive is a string. And that's what makes oneOf work. You can't change it inside of a oneOf branch, to object type
