### ISSUE TITLE
Date Input type

### ISSUE THREAD

**Issue by willcode4food** [ismaelga/react-json-editor#19]
I am interested in adding a schema type called 'date'.  I envision this to render a calendar style date picker.   I was looking at this component to integrate.  https://github.com/Rudeg/react-input-calendar

Any thoughts or concerns?

**Comment by ismaelga** [comment]
You can do it with a custom input handler. See how to do it here: https://github.com/ismaelga/react-json-editor/blob/master/README.md#user-defined-input-component-example

**Comment by willcode4food** [comment]
great.  Thanks,
