### ISSUE TITLE
not compatible with react 15.0.0

### ISSUE THREAD

**Issue by tecnosegugio** [ismaelga/react-json-editor#24]
After ReactJS was updated to version 15, installing react-json-editor I got this error:

npm ERR! peerinvalid Peer react-json-editor@0.2.0 wants react@>=0.12.2 <1.0.0

If I edit package.json in order to install React 15.x, react-json-editor works fine so it looks like just a version check to amend.

**Comment by newbreedofgeek** [comment]
@tecnosegugio I'm having the same issue. If I just copy the 'dist' and include it locally it seems to work fine with react 15.0.0. 

@ismaelga @martijnvermaat does the peer-dependency to "react": ">=0.12.2 <1.0.0" really need to be there or is it some old artefact. I'll really like to use this as part of npm.

**Comment by walkerrandolphsmith** [comment]
Peer dependencies are meant for the consumer of the package to directly depend on a specific version of the peer dependency. If you are using a version of the React that is not in the described range, then you'll receive this error. Is this package compatible with React v15.0.0 interface? If so changing the peer decency range is sufficient. I can pick this up if no one is looking into it.

**Comment by ismaelga** [comment]
@walkerrandolphsmith Please do!

I think it is fully compatible with React v15 as is. Might need just some minor changes

**Comment by walkerrandolphsmith** [comment]
Sorry I have not been able to review this as I would have liked. If anyone wants to pick it up before me go ahead. I'll try to focus on this in the coming week.

**Comment by ismaelga** [comment]
Fixed on latest release
