### ISSUE TITLE
No compatible version found: react-dom@<16.0.0^0.14.6

### ISSUE THREAD

**Issue by hagitarowe** [ismaelga/react-json-editor#33]
To replicate:
git clone https://github.com/ismaelga/react-json-editor/
npm install

<img width="882" alt="screen shot 2017-06-21 at 3 36 42 pm" src="https://user-images.githubusercontent.com/8771924/27409652-7a00f194-5697-11e7-9332-1e988770f55a.png">

**Comment by ismaelga** [comment]
Fixed. Ty
