### ISSUE TITLE
'NODE_ENV' of undefined

### ISSUE THREAD

**Issue by moluv00** [ismaelga/react-json-editor#9]
Great app!

I just cloned the react-json-editor repo, did executed 'npm install', 'npm build', and 'npm start' commands to launch the site at '0.0.0.0:3000'. After which, I got some messages in the terminal with the final line that said.

```
'webpack:bundle is now VALID.'
```

When I went to the URL I got a blank screen. When I looked at the console I got the following message:

```
Uncaught TypeError: Cannot read property 'NODE_ENV' of undefined -webpack:///./~/react/lib/ReactPerf.js?:38
```

It is entirely possible that I did something wrong and missed a necessary step, but if you have any suggestions on the proper install procedure I'm all ears.

**Comment by ismaelga** [comment]
Thanks for trying out this lib. `npm start` is kind of a legacy script. If you want to run the demo page locally you can do `npm run gh-pages`.

Keep in mind that reac-json-editor is intended to be used as a dependency in your app and not as a standalone app.

**Comment by moluv00** [comment]
Thanks for the response. I understand the dependency setup. I was just having trouble trying to get the demo to work.  I'll see if the `npm run gh-pages` command helps at all.

**Comment by ismaelga** [comment]
Closing in hope you got it working

**Comment by ismaelga** [comment]
Ok, sorry for the misleading info. `npm run gh-pages` only builds them. If you want to open them you have to open the `./gh-pages/index.html` file that it generated.

**Comment by moluv00** [comment]
Thanks for the update.
- M

On Tue, Jan 19, 2016 at 2:08 PM, Ismael Abreu notifications@github.com
wrote:

> Ok, sorry for the misleading info. npm run gh-pages only builds them. If
> you want to open them you have to open the ./gh-pages/index.html file
> that it generated.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ismaelga/react-json-editor/issues/9#issuecomment-173003634
> .

## 

# 

http://blog.mwright.com
Fairness Advocate

https://mwright.com
Maurice Wright Note and Bookmarking
